-- Populating 224 county list
INSERT INTO public.countries(name, iso3, flag_url)
VALUES
('Afghanistan', 'AFG', 'https://www.preventionweb.net/assets/shared/images/flags/afg.jpg'),
('Albania', 'ALB', 'https://www.preventionweb.net/assets/shared/images/flags/alb.jpg'),
('Algeria', 'DZA', 'https://www.preventionweb.net/assets/shared/images/flags/dza.jpg'),
('American Samoa', 'ASM', 'https://www.preventionweb.net/assets/shared/images/flags/asm.jpg'),
('Andorra', 'AND', 'https://www.preventionweb.net/assets/shared/images/flags/and.jpg'),
('Angola', 'AGO', 'https://www.preventionweb.net/assets/shared/images/flags/ago.jpg'),
('Anguilla', 'AIA', 'https://www.preventionweb.net/assets/shared/images/flags/aia.jpg'),
('Antigua and Barbuda', 'ATG', 'https://www.preventionweb.net/assets/shared/images/flags/atg.jpg'),
('Argentina', 'ARG', 'https://www.preventionweb.net/assets/shared/images/flags/arg.jpg'),
('Armenia', 'ARM', 'https://www.preventionweb.net/assets/shared/images/flags/arm.jpg'),
('Aruba', 'ABW', 'https://www.preventionweb.net/assets/shared/images/flags/abw.jpg'),
('Australia', 'AUS', 'https://www.preventionweb.net/assets/shared/images/flags/aus.jpg'),
('Austria', 'AUT', 'https://www.preventionweb.net/assets/shared/images/flags/aut.jpg'),
('Azerbaijan', 'AZE', 'https://www.preventionweb.net/assets/shared/images/flags/aze.jpg'),
('Bahamas', 'BHS', 'https://www.preventionweb.net/assets/shared/images/flags/bhs.jpg'),
('Bahrain', 'BHR', 'https://www.preventionweb.net/assets/shared/images/flags/bhr.jpg'),
('Bangladesh', 'BGD', 'https://www.preventionweb.net/assets/shared/images/flags/bgd.jpg'),
('Barbados', 'BRB', 'https://www.preventionweb.net/assets/shared/images/flags/brb.jpg'),
('Belarus', 'BLR', 'https://www.preventionweb.net/assets/shared/images/flags/blr.jpg'),
('Belgium', 'BEL', 'https://www.preventionweb.net/assets/shared/images/flags/bel.jpg'),
('Belize', 'BLZ', 'https://www.preventionweb.net/assets/shared/images/flags/blz.jpg'),
('Benin', 'BEN', 'https://www.preventionweb.net/assets/shared/images/flags/ben.jpg'),
('Bermuda', 'BMU', 'https://www.preventionweb.net/assets/shared/images/flags/bmu.jpg'),
('Bhutan', 'BTN', 'https://www.preventionweb.net/assets/shared/images/flags/btn.jpg'),
('Bolivia, Plurinational State of', 'BOL', 'https://www.preventionweb.net/assets/shared/images/flags/bol.jpg'),
('Bosnia and Herzegovina', 'BIH', 'https://www.preventionweb.net/assets/shared/images/flags/bih.jpg'),
('Botswana', 'BWA', 'https://www.preventionweb.net/assets/shared/images/flags/bwa.jpg'),
('Brazil', 'BRA', 'https://www.preventionweb.net/assets/shared/images/flags/bra.jpg'),
('British Virgin Islands', 'VGB', 'https://www.preventionweb.net/assets/shared/images/flags/vgb.jpg'),
('Brunei Darussalam', 'BRN', 'https://www.preventionweb.net/assets/shared/images/flags/brn.jpg'),
('Bulgaria', 'BGR', 'https://www.preventionweb.net/assets/shared/images/flags/bgr.jpg'),
('Burkina Faso', 'BFA', 'https://www.preventionweb.net/assets/shared/images/flags/bfa.jpg'),
('Burundi', 'BDI', 'https://www.preventionweb.net/assets/shared/images/flags/bdi.jpg'),
('Cabo Verde', 'CPV', 'https://www.preventionweb.net/assets/shared/images/flags/cpv.jpg'),
('Cambodia', 'KHM', 'https://www.preventionweb.net/assets/shared/images/flags/khm.jpg'),
('Cameroon', 'CMR', 'https://www.preventionweb.net/assets/shared/images/flags/cmr.jpg'),
('Canada', 'CAN', 'https://www.preventionweb.net/assets/shared/images/flags/can.jpg'),
('Cayman Islands', 'CYM', 'https://www.preventionweb.net/assets/shared/images/flags/cym.jpg'),
('Central African Republic', 'CAF', 'https://www.preventionweb.net/assets/shared/images/flags/caf.jpg'),
('Chad', 'TCD', 'https://www.preventionweb.net/assets/shared/images/flags/tcd.jpg'),
('Chile', 'CHL', 'https://www.preventionweb.net/assets/shared/images/flags/chl.jpg'),
('China', 'CHN', 'https://www.preventionweb.net/assets/shared/images/flags/chn.jpg'),
('Colombia', 'COL', 'https://www.preventionweb.net/assets/shared/images/flags/col.jpg'),
('Comoros', 'COM', 'https://www.preventionweb.net/assets/shared/images/flags/com.jpg'),
('Democratic Republic of the Congo', 'COD', 'https://www.preventionweb.net/assets/shared/images/flags/cod.jpg'),
('Republic of the Congo', 'COG', 'https://www.preventionweb.net/assets/shared/images/flags/cog.jpg'),
('Cook Islands', 'COK', 'https://www.preventionweb.net/assets/shared/images/flags/cok.jpg'),
('Costa Rica', 'CRI', 'https://www.preventionweb.net/assets/shared/images/flags/cri.jpg'),
('Côte d&#039;Ivoire', 'CIV', 'https://www.preventionweb.net/assets/shared/images/flags/civ.jpg'),
('Croatia', 'HRV', 'https://www.preventionweb.net/assets/shared/images/flags/hrv.jpg'),
('Cuba', 'CUB', 'https://www.preventionweb.net/assets/shared/images/flags/cub.jpg'),
('Cyprus', 'CYP', 'https://www.preventionweb.net/assets/shared/images/flags/cyp.jpg'),
('Czech Republic', 'CZE', 'https://www.preventionweb.net/assets/shared/images/flags/cze.jpg'),
('Denmark', 'DNK', 'https://www.preventionweb.net/assets/shared/images/flags/dnk.jpg'),
('Djibouti', 'DJI', 'https://www.preventionweb.net/assets/shared/images/flags/dji.jpg'),
('Dominica', 'DMA', 'https://www.preventionweb.net/assets/shared/images/flags/dma.jpg'),
('Dominican Republic', 'DOM', 'https://www.preventionweb.net/assets/shared/images/flags/dom.jpg'),
('Ecuador', 'ECU', 'https://www.preventionweb.net/assets/shared/images/flags/ecu.jpg'),
('Egypt', 'EGY', 'https://www.preventionweb.net/assets/shared/images/flags/egy.jpg'),
('El Salvador', 'SLV', 'https://www.preventionweb.net/assets/shared/images/flags/slv.jpg'),
('Equatorial Guinea', 'GNQ', 'https://www.preventionweb.net/assets/shared/images/flags/gnq.jpg'),
('Eritrea', 'ERI', 'https://www.preventionweb.net/assets/shared/images/flags/eri.jpg'),
('Estonia', 'EST', 'https://www.preventionweb.net/assets/shared/images/flags/est.jpg'),
('Eswatini', 'SWZ', 'https://www.preventionweb.net/assets/shared/images/flags/swz.jpg'),
('Ethiopia', 'ETH', 'https://www.preventionweb.net/assets/shared/images/flags/eth.jpg'),
('Fiji', 'FJI', 'https://www.preventionweb.net/assets/shared/images/flags/fji.jpg'),
('Finland', 'FIN', 'https://www.preventionweb.net/assets/shared/images/flags/fin.jpg'),
('France', 'FRA', 'https://www.preventionweb.net/assets/shared/images/flags/fra.jpg'),
('French Guiana', 'GUF', 'https://www.preventionweb.net/assets/shared/images/flags/guf.jpg'),
('French Polynesia', 'PYF', 'https://www.preventionweb.net/assets/shared/images/flags/pyf.jpg'),
('Gabon', 'GAB', 'https://www.preventionweb.net/assets/shared/images/flags/gab.jpg'),
('Gambia, Republic of The', 'GMB', 'https://www.preventionweb.net/assets/shared/images/flags/gmb.jpg'),
('Georgia', 'GEO', 'https://www.preventionweb.net/assets/shared/images/flags/geo.jpg'),
('Germany', 'DEU', 'https://www.preventionweb.net/assets/shared/images/flags/deu.jpg'),
('Ghana', 'GHA', 'https://www.preventionweb.net/assets/shared/images/flags/gha.jpg'),
('Greece', 'GRC', 'https://www.preventionweb.net/assets/shared/images/flags/grc.jpg'),
('Grenada', 'GRD', 'https://www.preventionweb.net/assets/shared/images/flags/grd.jpg'),
('Guadeloupe', 'GLP', 'https://www.preventionweb.net/assets/shared/images/flags/glp.jpg'),
('Guam', 'GUM', 'https://www.preventionweb.net/assets/shared/images/flags/gum.jpg'),
('Guatemala', 'GTM', 'https://www.preventionweb.net/assets/shared/images/flags/gtm.jpg'),
('Guinea', 'GIN', 'https://www.preventionweb.net/assets/shared/images/flags/gin.jpg'),
('Guinea-Bissau', 'GNB', 'https://www.preventionweb.net/assets/shared/images/flags/gnb.jpg'),
('Guyana', 'GUY', 'https://www.preventionweb.net/assets/shared/images/flags/guy.jpg'),
('Haiti', 'HTI', 'https://www.preventionweb.net/assets/shared/images/flags/hti.jpg'),
('Holy See', 'VAT', 'https://www.preventionweb.net/assets/shared/images/flags/vat.jpg'),
('Honduras', 'HND', 'https://www.preventionweb.net/assets/shared/images/flags/hnd.jpg'),
('Hong Kong (China)', 'HKG', 'https://www.preventionweb.net/assets/shared/images/flags/hkg.jpg'),
('Hungary', 'HUN', 'https://www.preventionweb.net/assets/shared/images/flags/hun.jpg'),
('Iceland', 'ISL', 'https://www.preventionweb.net/assets/shared/images/flags/isl.jpg'),
('India', 'IND', 'https://www.preventionweb.net/assets/shared/images/flags/ind.jpg'),
('Indonesia', 'IDN', 'https://www.preventionweb.net/assets/shared/images/flags/idn.jpg'),
('Iran, Islamic Rep of', 'IRN', 'https://www.preventionweb.net/assets/shared/images/flags/irn.jpg'),
('Iraq', 'IRQ', 'https://www.preventionweb.net/assets/shared/images/flags/irq.jpg'),
('Ireland', 'IRL', 'https://www.preventionweb.net/assets/shared/images/flags/irl.jpg'),
('Israel', 'ISR', 'https://www.preventionweb.net/assets/shared/images/flags/isr.jpg'),
('Italy', 'ITA', 'https://www.preventionweb.net/assets/shared/images/flags/ita.jpg'),
('Jamaica', 'JAM', 'https://www.preventionweb.net/assets/shared/images/flags/jam.jpg'),
('Japan', 'JPN', 'https://www.preventionweb.net/assets/shared/images/flags/jpn.jpg'),
('Jordan', 'JOR', 'https://www.preventionweb.net/assets/shared/images/flags/jor.jpg'),
('Kazakhstan', 'KAZ', 'https://www.preventionweb.net/assets/shared/images/flags/kaz.jpg'),
('Kenya', 'KEN', 'https://www.preventionweb.net/assets/shared/images/flags/ken.jpg'),
('Kiribati', 'KIR', 'https://www.preventionweb.net/assets/shared/images/flags/kir.jpg'),
('Korea, Dem People&#039;s Rep of', 'PRK', 'https://www.preventionweb.net/assets/shared/images/flags/prk.jpg'),
('Korea, Rep of', 'KOR', 'https://www.preventionweb.net/assets/shared/images/flags/kor.jpg'),
('Kuwait', 'KWT', 'https://www.preventionweb.net/assets/shared/images/flags/kwt.jpg'),
('Kyrgyzstan', 'KGZ', 'https://www.preventionweb.net/assets/shared/images/flags/kgz.jpg'),
('Lao People&#039;s Democratic Republic', 'LAO', 'https://www.preventionweb.net/assets/shared/images/flags/lao.jpg'),
('Latvia', 'LVA', 'https://www.preventionweb.net/assets/shared/images/flags/lva.jpg'),
('Lebanon', 'LBN', 'https://www.preventionweb.net/assets/shared/images/flags/lbn.jpg'),
('Lesotho', 'LSO', 'https://www.preventionweb.net/assets/shared/images/flags/lso.jpg'),
('Liberia', 'LBR', 'https://www.preventionweb.net/assets/shared/images/flags/lbr.jpg'),
('Libya', 'LBY', 'https://www.preventionweb.net/assets/shared/images/flags/lby.jpg'),
('Liechtenstein', 'LIE', 'https://www.preventionweb.net/assets/shared/images/flags/lie.jpg'),
('Lithuania', 'LTU', 'https://www.preventionweb.net/assets/shared/images/flags/ltu.jpg'),
('Luxembourg', 'LUX', 'https://www.preventionweb.net/assets/shared/images/flags/lux.jpg'),
('Macao (China)', 'MAC', 'https://www.preventionweb.net/assets/shared/images/flags/mac.jpg'),
('Madagascar', 'MDG', 'https://www.preventionweb.net/assets/shared/images/flags/mdg.jpg'),
('Malawi', 'MWI', 'https://www.preventionweb.net/assets/shared/images/flags/mwi.jpg'),
('Malaysia', 'MYS', 'https://www.preventionweb.net/assets/shared/images/flags/mys.jpg'),
('Maldives', 'MDV', 'https://www.preventionweb.net/assets/shared/images/flags/mdv.jpg'),
('Mali', 'MLI', 'https://www.preventionweb.net/assets/shared/images/flags/mli.jpg'),
('Malta', 'MLT', 'https://www.preventionweb.net/assets/shared/images/flags/mlt.jpg'),
('Marshall Islands', 'MHL', 'https://www.preventionweb.net/assets/shared/images/flags/mhl.jpg'),
('Martinique', 'MTQ', 'https://www.preventionweb.net/assets/shared/images/flags/mtq.jpg'),
('Mauritania', 'MRT', 'https://www.preventionweb.net/assets/shared/images/flags/mrt.jpg'),
('Mauritius', 'MUS', 'https://www.preventionweb.net/assets/shared/images/flags/mus.jpg'),
('Mayotte', 'MYT', 'https://www.preventionweb.net/assets/shared/images/flags/myt.jpg'),
('Mexico', 'MEX', 'https://www.preventionweb.net/assets/shared/images/flags/mex.jpg'),
('Micronesia, Fed States of', 'FSM', 'https://www.preventionweb.net/assets/shared/images/flags/fsm.jpg'),
('Republic of Moldova', 'MDA', 'https://www.preventionweb.net/assets/shared/images/flags/mda.jpg'),
('Monaco', 'MCO', 'https://www.preventionweb.net/assets/shared/images/flags/mco.jpg'),
('Mongolia', 'MNG', 'https://www.preventionweb.net/assets/shared/images/flags/mng.jpg'),
('Montenegro', 'MNE', 'https://www.preventionweb.net/assets/shared/images/flags/mne.jpg'),
('Montserrat', 'MSR', 'https://www.preventionweb.net/assets/shared/images/flags/msr.jpg'),
('Morocco', 'MAR', 'https://www.preventionweb.net/assets/shared/images/flags/mar.jpg'),
('Mozambique', 'MOZ', 'https://www.preventionweb.net/assets/shared/images/flags/moz.jpg'),
('Myanmar', 'MMR', 'https://www.preventionweb.net/assets/shared/images/flags/mmr.jpg'),
('Namibia', 'NAM', 'https://www.preventionweb.net/assets/shared/images/flags/nam.jpg'),
('Nauru', 'NRU', 'https://www.preventionweb.net/assets/shared/images/flags/nru.jpg'),
('Nepal', 'NPL', 'https://www.preventionweb.net/assets/shared/images/flags/npl.jpg'),
('Netherlands, the', 'NLD', 'https://www.preventionweb.net/assets/shared/images/flags/nld.jpg'),
('New Caledonia', 'NCL', 'https://www.preventionweb.net/assets/shared/images/flags/ncl.jpg'),
('New Zealand', 'NZL', 'https://www.preventionweb.net/assets/shared/images/flags/nzl.jpg'),
('Nicaragua', 'NIC', 'https://www.preventionweb.net/assets/shared/images/flags/nic.jpg'),
('Niger', 'NER', 'https://www.preventionweb.net/assets/shared/images/flags/ner.jpg'),
('Nigeria', 'NGA', 'https://www.preventionweb.net/assets/shared/images/flags/nga.jpg'),
('Niue', 'NIU', 'https://www.preventionweb.net/assets/shared/images/flags/niu.jpg'),
('Norfolk Island', 'NFK', 'https://www.preventionweb.net/assets/shared/images/flags/nfk.jpg'),
('North Macedonia', 'MKD', 'https://www.preventionweb.net/assets/shared/images/flags/mkd.jpg'),
('Northern Mariana Islands', 'MNP', 'https://www.preventionweb.net/assets/shared/images/flags/mnp.jpg'),
('Norway', 'NOR', 'https://www.preventionweb.net/assets/shared/images/flags/nor.jpg'),
('Oman', 'OMN', 'https://www.preventionweb.net/assets/shared/images/flags/omn.jpg'),
('Pakistan', 'PAK', 'https://www.preventionweb.net/assets/shared/images/flags/pak.jpg'),
('Palau', 'PLW', 'https://www.preventionweb.net/assets/shared/images/flags/plw.jpg'),
('Palestine, State of', 'PSE', 'https://www.preventionweb.net/assets/shared/images/flags/pse.jpg'),
('Panama', 'PAN', 'https://www.preventionweb.net/assets/shared/images/flags/pan.jpg'),
('Papua New Guinea', 'PNG', 'https://www.preventionweb.net/assets/shared/images/flags/png.jpg'),
('Paraguay', 'PRY', 'https://www.preventionweb.net/assets/shared/images/flags/pry.jpg'),
('Peru', 'PER', 'https://www.preventionweb.net/assets/shared/images/flags/per.jpg'),
('Philippines', 'PHL', 'https://www.preventionweb.net/assets/shared/images/flags/phl.jpg'),
('Poland', 'POL', 'https://www.preventionweb.net/assets/shared/images/flags/pol.jpg'),
('Portugal', 'PRT', 'https://www.preventionweb.net/assets/shared/images/flags/prt.jpg'),
('Puerto Rico', 'PRI', 'https://www.preventionweb.net/assets/shared/images/flags/pri.jpg'),
('Qatar', 'QAT', 'https://www.preventionweb.net/assets/shared/images/flags/qat.jpg'),
('Reunion', 'REU', 'https://www.preventionweb.net/assets/shared/images/flags/reu.jpg'),
('Romania', 'ROU', 'https://www.preventionweb.net/assets/shared/images/flags/rou.jpg'),
('Russian Federation', 'RUS', 'https://www.preventionweb.net/assets/shared/images/flags/rus.jpg'),
('Rwanda', 'RWA', 'https://www.preventionweb.net/assets/shared/images/flags/rwa.jpg'),
('Saint Kitts and Nevis', 'KNA', 'https://www.preventionweb.net/assets/shared/images/flags/kna.jpg'),
('Saint Lucia', 'LCA', 'https://www.preventionweb.net/assets/shared/images/flags/lca.jpg'),
('Saint Pierre and Miquelon', 'SPM', 'https://www.preventionweb.net/assets/shared/images/flags/spm.jpg'),
('Saint Vincent and the Grenadines', 'VCT', 'https://www.preventionweb.net/assets/shared/images/flags/vct.jpg'),
('Samoa', 'WSM', 'https://www.preventionweb.net/assets/shared/images/flags/wsm.jpg'),
('San Marino', 'SMR', 'https://www.preventionweb.net/assets/shared/images/flags/smr.jpg'),
('Sao Tome and Principe', 'STP', 'https://www.preventionweb.net/assets/shared/images/flags/stp.jpg'),
('Saudi Arabia', 'SAU', 'https://www.preventionweb.net/assets/shared/images/flags/sau.jpg'),
('Senegal', 'SEN', 'https://www.preventionweb.net/assets/shared/images/flags/sen.jpg'),
('Serbia', 'SRB', 'https://www.preventionweb.net/assets/shared/images/flags/srb.jpg'),
('Seychelles', 'SYC', 'https://www.preventionweb.net/assets/shared/images/flags/syc.jpg'),
('Sierra Leone', 'SLE', 'https://www.preventionweb.net/assets/shared/images/flags/sle.jpg'),
('Singapore', 'SGP', 'https://www.preventionweb.net/assets/shared/images/flags/sgp.jpg'),
('Slovakia', 'SVK', 'https://www.preventionweb.net/assets/shared/images/flags/svk.jpg'),
('Slovenia', 'SVN', 'https://www.preventionweb.net/assets/shared/images/flags/svn.jpg'),
('Solomon Islands', 'SLB', 'https://www.preventionweb.net/assets/shared/images/flags/slb.jpg'),
('Somalia', 'SOM', 'https://www.preventionweb.net/assets/shared/images/flags/som.jpg'),
('South Africa', 'ZAF', 'https://www.preventionweb.net/assets/shared/images/flags/zaf.jpg'),
('South Sudan', 'SSD', 'https://www.preventionweb.net/assets/shared/images/flags/ssd.jpg'),
('Spain', 'ESP', 'https://www.preventionweb.net/assets/shared/images/flags/esp.jpg'),
('Sri Lanka', 'LKA', 'https://www.preventionweb.net/assets/shared/images/flags/lka.jpg'),
('Sudan', 'SDN', 'https://www.preventionweb.net/assets/shared/images/flags/sdn.jpg'),
('Suriname', 'SUR', 'https://www.preventionweb.net/assets/shared/images/flags/sur.jpg'),
('Sweden', 'SWE', 'https://www.preventionweb.net/assets/shared/images/flags/swe.jpg'),
('Switzerland', 'CHE', 'https://www.preventionweb.net/assets/shared/images/flags/che.jpg'),
('Syrian Arab Republic', 'SYR', 'https://www.preventionweb.net/assets/shared/images/flags/syr.jpg'),
('Tajikistan', 'TJK', 'https://www.preventionweb.net/assets/shared/images/flags/tjk.jpg'),
('Tanzania, United Rep of', 'TZA', 'https://www.preventionweb.net/assets/shared/images/flags/tza.jpg'),
('Thailand', 'THA', 'https://www.preventionweb.net/assets/shared/images/flags/tha.jpg'),
('Timor-Leste', 'TLS', 'https://www.preventionweb.net/assets/shared/images/flags/tls.jpg'),
('Togo', 'TGO', 'https://www.preventionweb.net/assets/shared/images/flags/tgo.jpg'),
('Tokelau', 'TKL', 'https://www.preventionweb.net/assets/shared/images/flags/tkl.jpg'),
('Tonga', 'TON', 'https://www.preventionweb.net/assets/shared/images/flags/ton.jpg'),
('Trinidad and Tobago', 'TTO', 'https://www.preventionweb.net/assets/shared/images/flags/tto.jpg'),
('Tunisia', 'TUN', 'https://www.preventionweb.net/assets/shared/images/flags/tun.jpg'),
('Türkiye', 'TUR', 'https://www.preventionweb.net/assets/shared/images/flags/tur.jpg'),
('Turkmenistan', 'TKM', 'https://www.preventionweb.net/assets/shared/images/flags/tkm.jpg'),
('Turks and Caicos Islands', 'TCA', 'https://www.preventionweb.net/assets/shared/images/flags/tca.jpg'),
('Tuvalu', 'TUV', 'https://www.preventionweb.net/assets/shared/images/flags/tuv.jpg'),
('Uganda', 'UGA', 'https://www.preventionweb.net/assets/shared/images/flags/uga.jpg'),
('Ukraine', 'UKR', 'https://www.preventionweb.net/assets/shared/images/flags/ukr.jpg'),
('United Arab Emirates', 'ARE', 'https://www.preventionweb.net/assets/shared/images/flags/are.jpg'),
('United Kingdom of Great Britain and Northern Ireland', 'GBR', 'https://www.preventionweb.net/assets/shared/images/flags/gbr.jpg'),
('United States of America', 'USA', 'https://www.preventionweb.net/assets/shared/images/flags/usa.jpg'),
('United States Virgin Islands', 'VIR', 'https://www.preventionweb.net/assets/shared/images/flags/vir.jpg'),
('Uruguay', 'URY', 'https://www.preventionweb.net/assets/shared/images/flags/ury.jpg'),
('Uzbekistan', 'UZB', 'https://www.preventionweb.net/assets/shared/images/flags/uzb.jpg'),
('Vanuatu', 'VUT', 'https://www.preventionweb.net/assets/shared/images/flags/vut.jpg'),
('Venezuela, Bolivarian Rep of', 'VEN', 'https://www.preventionweb.net/assets/shared/images/flags/ven.jpg'),
('Viet Nam', 'VNM', 'https://www.preventionweb.net/assets/shared/images/flags/vnm.jpg'),
('Wallis and Futuna Islands', 'WLF', 'https://www.preventionweb.net/assets/shared/images/flags/wlf.jpg'),
('Yemen', 'YEM', 'https://www.preventionweb.net/assets/shared/images/flags/yem.jpg'),
('Zambia', 'ZMB', 'https://www.preventionweb.net/assets/shared/images/flags/zmb.jpg'),
('Zimbabwe', 'ZWE', 'https://www.preventionweb.net/assets/shared/images/flags/zwe.jpg'),
('Sint Maarten', 'SXM', ''),
('Saint Martin', 'MAF', '');