-- Custom SQL migration file to update countries table with ISO3 codes
UPDATE public.countries SET iso3 = CASE name
    WHEN 'Afghanistan' THEN 'AFG'
    WHEN 'Albania' THEN 'ALB'
    WHEN 'Algeria' THEN 'DZA'
    WHEN 'Andorra' THEN 'AND'
    WHEN 'Angola' THEN 'AGO'
    WHEN 'Antigua and Barbuda' THEN 'ATG'
    WHEN 'Argentina' THEN 'ARG'
    WHEN 'Armenia' THEN 'ARM'
    WHEN 'Australia' THEN 'AUS'
    WHEN 'Austria' THEN 'AUT'
    WHEN 'Azerbaijan' THEN 'AZE'
    WHEN 'Bahamas' THEN 'BHS'
    WHEN 'Bahrain' THEN 'BHR'
    WHEN 'Bangladesh' THEN 'BGD'
    WHEN 'Barbados' THEN 'BRB'
    WHEN 'Belarus' THEN 'BLR'
    WHEN 'Belgium' THEN 'BEL'
    WHEN 'Belize' THEN 'BLZ'
    WHEN 'Benin' THEN 'BEN'
    WHEN 'Bhutan' THEN 'BTN'
    WHEN 'Bolivia' THEN 'BOL'
    WHEN 'Bosnia and Herzegovina' THEN 'BIH'
    WHEN 'Botswana' THEN 'BWA'
    WHEN 'Brazil' THEN 'BRA'
    WHEN 'Brunei' THEN 'BRN'
    WHEN 'Bulgaria' THEN 'BGR'
    WHEN 'Burkina Faso' THEN 'BFA'
    WHEN 'Burundi' THEN 'BDI'
    WHEN 'Cabo Verde' THEN 'CPV'
    WHEN 'Cambodia' THEN 'KHM'
    WHEN 'Cameroon' THEN 'CMR'
    WHEN 'Canada' THEN 'CAN'
    WHEN 'Central African Republic' THEN 'CAF'
    WHEN 'Chad' THEN 'TCD'
    WHEN 'Chile' THEN 'CHL'
    WHEN 'China' THEN 'CHN'
    WHEN 'Colombia' THEN 'COL'
    WHEN 'Comoros' THEN 'COM'
    WHEN 'Congo' THEN 'COG'
    WHEN 'Costa Rica' THEN 'CRI'
    WHEN 'Croatia' THEN 'HRV'
    WHEN 'Cuba' THEN 'CUB'
    WHEN 'Cyprus' THEN 'CYP'
    WHEN 'Czech Republic' THEN 'CZE'
    WHEN 'Democratic Republic of the Congo' THEN 'COD'
    WHEN 'Denmark' THEN 'DNK'
    WHEN 'Djibouti' THEN 'DJI'
    WHEN 'Dominica' THEN 'DMA'
    WHEN 'Dominican Republic' THEN 'DOM'
    WHEN 'Ecuador' THEN 'ECU'
    WHEN 'Egypt' THEN 'EGY'
    WHEN 'El Salvador' THEN 'SLV'
    WHEN 'Equatorial Guinea' THEN 'GNQ'
    WHEN 'Eritrea' THEN 'ERI'
    WHEN 'Estonia' THEN 'EST'
    WHEN 'Eswatini' THEN 'SWZ'
    WHEN 'Ethiopia' THEN 'ETH'
    WHEN 'Fiji' THEN 'FJI'
    WHEN 'Finland' THEN 'FIN'
    WHEN 'France' THEN 'FRA'
    WHEN 'Gabon' THEN 'GAB'
    WHEN 'Gambia' THEN 'GMB'
    WHEN 'Georgia' THEN 'GEO'
    WHEN 'Germany' THEN 'DEU'
    WHEN 'Ghana' THEN 'GHA'
    WHEN 'Greece' THEN 'GRC'
    WHEN 'Grenada' THEN 'GRD'
    WHEN 'Guatemala' THEN 'GTM'
    WHEN 'Guinea' THEN 'GIN'
    WHEN 'Guinea-Bissau' THEN 'GNB'
    WHEN 'Guyana' THEN 'GUY'
    WHEN 'Haiti' THEN 'HTI'
    WHEN 'Honduras' THEN 'HND'
    WHEN 'Hungary' THEN 'HUN'
    WHEN 'Iceland' THEN 'ISL'
    WHEN 'India' THEN 'IND'
    WHEN 'Indonesia' THEN 'IDN'
    WHEN 'Iran' THEN 'IRN'
    WHEN 'Iraq' THEN 'IRQ'
    WHEN 'Ireland' THEN 'IRL'
    WHEN 'Israel' THEN 'ISR'
    WHEN 'Italy' THEN 'ITA'
    WHEN 'Jamaica' THEN 'JAM'
    WHEN 'Japan' THEN 'JPN'
    WHEN 'Jordan' THEN 'JOR'
    WHEN 'Kazakhstan' THEN 'KAZ'
    WHEN 'Kenya' THEN 'KEN'
    WHEN 'Kiribati' THEN 'KIR'
    WHEN 'Kuwait' THEN 'KWT'
    WHEN 'Kyrgyzstan' THEN 'KGZ'
    WHEN 'Laos' THEN 'LAO'
    WHEN 'Latvia' THEN 'LVA'
    WHEN 'Lebanon' THEN 'LBN'
    WHEN 'Lesotho' THEN 'LSO'
    WHEN 'Liberia' THEN 'LBR'
    WHEN 'Libya' THEN 'LBY'
    WHEN 'Liechtenstein' THEN 'LIE'
    WHEN 'Lithuania' THEN 'LTU'
    WHEN 'Luxembourg' THEN 'LUX'
    WHEN 'Madagascar' THEN 'MDG'
    WHEN 'Malawi' THEN 'MWI'
    WHEN 'Malaysia' THEN 'MYS'
    WHEN 'Maldives' THEN 'MDV'
    WHEN 'Mali' THEN 'MLI'
    WHEN 'Malta' THEN 'MLT'
    WHEN 'Marshall Islands' THEN 'MHL'
    WHEN 'Mauritania' THEN 'MRT'
    WHEN 'Mauritius' THEN 'MUS'
    WHEN 'Mexico' THEN 'MEX'
    WHEN 'Micronesia' THEN 'FSM'
    WHEN 'Moldova' THEN 'MDA'
    WHEN 'Monaco' THEN 'MCO'
    WHEN 'Mongolia' THEN 'MNG'
    WHEN 'Montenegro' THEN 'MNE'
    WHEN 'Morocco' THEN 'MAR'
    WHEN 'Mozambique' THEN 'MOZ'
    WHEN 'Myanmar' THEN 'MMR'
    WHEN 'Namibia' THEN 'NAM'
    WHEN 'Nauru' THEN 'NRU'
    WHEN 'Nepal' THEN 'NPL'
    WHEN 'Netherlands' THEN 'NLD'
    WHEN 'New Zealand' THEN 'NZL'
    WHEN 'Nicaragua' THEN 'NIC'
    WHEN 'Niger' THEN 'NER'
    WHEN 'Nigeria' THEN 'NGA'
    WHEN 'North Korea' THEN 'PRK'
    WHEN 'North Macedonia' THEN 'MKD'
    WHEN 'Norway' THEN 'NOR'
    WHEN 'Oman' THEN 'OMN'
    WHEN 'Pakistan' THEN 'PAK'
    WHEN 'Palau' THEN 'PLW'
    WHEN 'Panama' THEN 'PAN'
    WHEN 'Papua New Guinea' THEN 'PNG'
    WHEN 'Paraguay' THEN 'PRY'
    WHEN 'Peru' THEN 'PER'
    WHEN 'Philippines' THEN 'PHL'
    WHEN 'Poland' THEN 'POL'
    WHEN 'Portugal' THEN 'PRT'
    WHEN 'Qatar' THEN 'QAT'
    WHEN 'Romania' THEN 'ROU'
    WHEN 'Russia' THEN 'RUS'
    WHEN 'Rwanda' THEN 'RWA'
    WHEN 'Saint Kitts and Nevis' THEN 'KNA'
    WHEN 'Saint Lucia' THEN 'LCA'
    WHEN 'Saint Vincent and the Grenadines' THEN 'VCT'
    WHEN 'Samoa' THEN 'WSM'
    WHEN 'San Marino' THEN 'SMR'
    WHEN 'Sao Tome and Principe' THEN 'STP'
    WHEN 'Saudi Arabia' THEN 'SAU'
    WHEN 'Senegal' THEN 'SEN'
    WHEN 'Serbia' THEN 'SRB'
    WHEN 'Seychelles' THEN 'SYC'
    WHEN 'Sierra Leone' THEN 'SLE'
    WHEN 'Singapore' THEN 'SGP'
    WHEN 'Slovakia' THEN 'SVK'
    WHEN 'Slovenia' THEN 'SVN'
    WHEN 'Solomon Islands' THEN 'SLB'
    WHEN 'Somalia' THEN 'SOM'
    WHEN 'South Africa' THEN 'ZAF'
    WHEN 'South Korea' THEN 'KOR'
    WHEN 'South Sudan' THEN 'SSD'
    WHEN 'Spain' THEN 'ESP'
    WHEN 'Sri Lanka' THEN 'LKA'
    WHEN 'Sudan' THEN 'SDN'
    WHEN 'Suriname' THEN 'SUR'
    WHEN 'Sweden' THEN 'SWE'
    WHEN 'Switzerland' THEN 'CHE'
    WHEN 'Syria' THEN 'SYR'
    WHEN 'Taiwan' THEN 'TWN'
    WHEN 'Tajikistan' THEN 'TJK'
    WHEN 'Tanzania' THEN 'TZA'
    WHEN 'Thailand' THEN 'THA'
    WHEN 'Timor-Leste' THEN 'TLS'
    WHEN 'Togo' THEN 'TGO'
    WHEN 'Tonga' THEN 'TON'
    WHEN 'Trinidad and Tobago' THEN 'TTO'
    WHEN 'Tunisia' THEN 'TUN'
    WHEN 'Turkey' THEN 'TUR'
    WHEN 'Turkmenistan' THEN 'TKM'
    WHEN 'Tuvalu' THEN 'TUV'
    WHEN 'Uganda' THEN 'UGA'
    WHEN 'Ukraine' THEN 'UKR'
    WHEN 'United Arab Emirates' THEN 'ARE'
    WHEN 'United Kingdom' THEN 'GBR'
    WHEN 'United States' THEN 'USA'
    WHEN 'Uruguay' THEN 'URY'
    WHEN 'Uzbekistan' THEN 'UZB'
    WHEN 'Vanuatu' THEN 'VUT'
    WHEN 'Vatican City' THEN 'VAT'
    WHEN 'Venezuela' THEN 'VEN'
    WHEN 'Vietnam' THEN 'VNM'
    WHEN 'Yemen' THEN 'YEM'
    WHEN 'Zambia' THEN 'ZMB'
    WHEN 'Zimbabwe' THEN 'ZWE'
    ELSE NULL
END;