
export const BASE_UPLOAD_PATH = "/uploads";
export const HAZARDOUS_EVENT_UPLOAD_PATH = `${BASE_UPLOAD_PATH}/hazardous-event`;
export const DISASTER_RECORDS_UPLOAD_PATH = `${BASE_UPLOAD_PATH}/disaster-record`;
export const DISASTER_RECORDS_LOSSES_UPLOAD_PATH = `${DISASTER_RECORDS_UPLOAD_PATH}/losses`;
export const DISASTER_RECORDS_DISRUPTIONS_UPLOAD_PATH = `${DISASTER_RECORDS_UPLOAD_PATH}/disruptions`;
export const DISASTER_RECORDS_DAMAGES_UPLOAD_PATH = `${DISASTER_RECORDS_UPLOAD_PATH}/damages`;



export const TEMP_UPLOAD_PATH = `${BASE_UPLOAD_PATH}/temp`;

