import { jwtDecode } from "jwt-decode";

import { 
	configSsoAzureB2C, 
	SSOAzureB2C
} from "~/util/config";

function _baseURL(): string {
    const jsonAzureB2C:SSOAzureB2C = configSsoAzureB2C();
    const baseURL = `https://${jsonAzureB2C.tenant}.b2clogin.com/${jsonAzureB2C.tenant}.onmicrosoft.com/oauth2/v2.0`;
    return baseURL;
}

/**
 * Get the Application Name.
 * 
 * @param value 
 * @returns string
 */
export function logiStep1GetCode(pRedirectURL:string): string {
    const jsonAzureB2C:SSOAzureB2C = configSsoAzureB2C();
    const userFlow = 'B2C_1_UN_UNDRR_SIGNUP_SIGNIN';
    let redirectURL = pRedirectURL.trim();
    redirectURL = encodeURIComponent(redirectURL);
    const url = `${_baseURL()}/authorize?p=${userFlow}&client_id=${jsonAzureB2C.client_id}&nonce=defaultNonce&redirect_uri=${redirectURL}&scope=openid+email&response_type=code&prompt=login`;

    //const urlSSOLogin= urlSSO + '/authorize?p='+ ssoAzureUserFlow +'&client_id='+ jsonAzureB2C.client_id +'&nonce=defaultNonce&redirect_uri='+ encodeURIComponent( jsonAzureB2C.redirect_url ) +'&scope=openid+email&response_type=code&prompt=login';

    // const token = "xeyJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsiLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE3MzAyODY4MzksIm5iZiI6MTczMDI4MzIzOSwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly91bmIyYy5iMmNsb2dpbi5jb20vMTQ1NmYzOWMtZWQ0ZC00ZjFhLThiYjUtNGRiZTE5YTg3YTBkL3YyLjAvIiwic3ViIjoiOGY0OGEyOTQtZmM2ZC00MTc4LWE4YzQtMGU1ZWE2NjAzNjkxIiwiYXVkIjoiOWQ5MDdjOWItZWRiNi00OTY5LTk0NjAtYzY4M2IxODQ1ZWI3Iiwibm9uY2UiOiJkZWZhdWx0Tm9uY2UiLCJpYXQiOjE3MzAyODMyMzksImF1dGhfdGltZSI6MTczMDI4MzIzOCwiaWRwX2FjY2Vzc190b2tlbiI6ImV5SjBlWEFpT2lKS1YxUWlMQ0p1YjI1alpTSTZJakYxUWtWUWJWZHdSVTVuZEhSTVpUQlBjalpyWTBvNGMxOTJWbE5HZVUxSWFtSnZjVnBCWWpsNGVEQWlMQ0poYkdjaU9pSlNVekkxTmlJc0luZzFkQ0k2SWpOUVlVczBSV1o1UWs1UmRUTkRkR3BaYzJFeldXMW9VVFZGTUNJc0ltdHBaQ0k2SWpOUVlVczBSV1o1UWs1UmRUTkRkR3BaYzJFeldXMW9VVFZGTUNKOS5leUpoZFdRaU9pSXdNREF3TURBd015MHdNREF3TFRBd01EQXRZekF3TUMwd01EQXdNREF3TURBd01EQWlMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwzTjBjeTUzYVc1a2IzZHpMbTVsZEM4d1pqbGxNelZrWWkwMU5EUm1MVFJtTmpBdFltUmpZeTAxWldFME1UWmxObVJqTnpBdklpd2lhV0YwSWpveE56TXdNamd5T1RNM0xDSnVZbVlpT2pFM016QXlPREk1TXpjc0ltVjRjQ0k2TVRjek1ESTROelkyT1N3aVlXTmpkQ0k2TUN3aVlXTnlJam9pTVNJc0ltRnBieUk2SWtGV1VVRnhMemhaUVVGQlFXRndla2xxWkdrelN5dGxSMFZyWlhRd2FWWlNiV1JwTTJsalMyNVBVRmsxTUcxT2ExWnhlbGxSV21veVFreEJXbXhDUVd0M1YwRmxOMjgyYm1SU1NqWjRlVkJFWVRaSE1GcDROM2xQV2pRdlluaFFUVzloYWpoelNtOVZVVVJOU2lzeVlXcGpNVU5HVTJwQlBTSXNJbUZ0Y2lJNld5SndkMlFpTENKdFptRWlYU3dpWVhCd1gyUnBjM0JzWVhsdVlXMWxJam9pVlU1Q01rTWdRVkJRSWl3aVlYQndhV1FpT2lJelpHUXdZemd4TlMwNU1tUmxMVFJrWTJVdFltWm1ZeTFoT1RVMllqYzJZall6WkdZaUxDSmhjSEJwWkdGamNpSTZJakVpTENKbVlXMXBiSGxmYm1GdFpTSTZJazFoY21kaGRHVWlMQ0puYVhabGJsOXVZVzFsSWpvaVNtOWxiQ0lzSW1sa2RIbHdJam9pZFhObGNpSXNJbWx3WVdSa2NpSTZJakV4TlM0NE55NDNPUzQxT0NJc0ltNWhiV1VpT2lKS2IyVnNJRTFoY21kaGRHVWlMQ0p2YVdRaU9pSmhNamMwTTJFeU9TMDVOR0ppTFRRMk5HSXRPV1E0WkMxbU5XWTNOamsyT1dNMlptRWlMQ0p2Ym5CeVpXMWZjMmxrSWpvaVV5MHhMVFV0TWpFdE5ERTROVEV6TkRVd05TMHlPRGMzTWpFd05EUXlMVE01TmpjNU9UYzVOVGt0TlRjNU9ETWlMQ0p3YkdGMFppSTZJak1pTENKd2RXbGtJam9pTVRBd016TkdSa1k1UXpoRFJrTkVPQ0lzSW5Kb0lqb2lNQzVCVTBWQk1ucFhaVVF3T1ZWWlJTMDVla1kyYTBaMVltTmpRVTFCUVVGQlFVRkJRVUYzUVVGQlFVRkJRVUZCUVdoQlJVMHVJaXdpYzJOd0lqb2lWWE5sY2k1U1pXRmtJSEJ5YjJacGJHVWdiM0JsYm1sa0lHVnRZV2xzSWl3aWMzVmlJam9pVEZkSFRqQklTekpPUzJwclRFRXhWVmhQVlRNdFNVVk1WWGxuWlRWdVRVMUpjelZMTjNGQk5FRm5SU0lzSW5SbGJtRnVkRjl5WldkcGIyNWZjMk52Y0dVaU9pSkZWU0lzSW5ScFpDSTZJakJtT1dVek5XUmlMVFUwTkdZdE5HWTJNQzFpWkdOakxUVmxZVFF4Tm1VMlpHTTNNQ0lzSW5WdWFYRjFaVjl1WVcxbElqb2liV0Z5WjJGMFpVQjFiaTV2Y21jaUxDSjFjRzRpT2lKdFlYSm5ZWFJsUUhWdUxtOXlaeUlzSW5WMGFTSTZJa3hzVWxkd2EybzBNVEJQVDI5RFpYQlBjSEJUUVVFaUxDSjJaWElpT2lJeExqQWlMQ0ozYVdSeklqcGJJbUkzT1daaVpqUmtMVE5sWmprdE5EWTRPUzA0TVRRekxUYzJZakU1TkdVNE5UVXdPU0pkTENKNGJYTmZhV1J5Wld3aU9pSXlJREVpTENKNGJYTmZjM1FpT25zaWMzVmlJam9pWlRsRE9VTlNUMDVEVWtaaFgwdGFkMVJZVTNsd2NsbHVNRnBrU2pZNFlWazJUa2hHWVc1bVNVRlhieUo5TENKNGJYTmZkR05rZENJNk1UUTBPRFEzTWpBME9Dd2llRzF6WDNSa1luSWlPaUpGVlNKOS5iRS1tUFA0cDFabkdyUzdsXzdZcmtaMGFLN3ZxbXhYbjRvT3IwTUJCR0JBZnNpUnNaRzVNUExDLWtaUTl6NVE1dE1zQ0RMMGgtcnUtUHVDbVRBTWkteTlsQUFNMTBEczVDUFpIZHozWmprQ3lYMF80WEdJZ01abDB0YlQ3Q3h1SEZKLVJQY010SEpfT2laOWZuN2FOXzhNREdYMl8taEE5NFFmcG4tTEpYU2tTQWJjNnJud3ZiWDFaWjJWUmN1YVlFY3oyd0tyMnZEaS1Qa21oMlpNenM2R3FvalJVdExaOWxETllzLXlscy1EeEkyQTBwcDI1RTJ4WUJ1eXJVYnpOckRNSVpZN2NmWW5GRElaV1VNU29VSC13ZnlmWFJuVFpRYUNMSVZnX0FHSWN2T3NtSzJOWlpGX1pCanhsSVZ2LVdzMFBkeUZhRm5EazVSejdwdE9pMXciLCJpZHAiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vMGY5ZTM1ZGItNTQ0Zi00ZjYwLWJkY2MtNWVhNDE2ZTZkYzcwL3YyLjAiLCJnaXZlbl9uYW1lIjoiSm9lbCIsImZhbWlseV9uYW1lIjoiTWFyZ2F0ZSIsIm9pZCI6IjhmNDhhMjk0LWZjNmQtNDE3OC1hOGM0LTBlNWVhNjYwMzY5MSIsImV4dGVuc2lvbl9Db21wYW55IjoiVU5EUlIiLCJleHRlbnNpb25fUG9zaXRpb24iOiJJbmZvIFN5c3RlbXMgT2ZmaWNlciIsInRmcCI6IkIyQ18xX1VOX1VORFJSX1NJR05VUF9TSUdOSU4ifQ.ndk0DFKIkfoLFtRNcCKuIrsnBx1Di0VQkdj6FXgn6G1Q-aKjiMAOJUm2zh-yKWH5--oXQJGQIkfQEOr6ukQD6eo9ovi2l54sNvZLVwkEf3EcQzNfUWllC8xgRhORliP0JYv1AL4zPsqmhyFy-cFofa-Ozon50zFcfj9fEI6WPEsSkY-gUokgGrAZUcaI5Nz5YpWj_K3vbXSy7yoTjI7R42lkzS_C2ETvh6QwaNK_1BR9YuSjW_PrWncevmJt_sD_nDg5ouignENFrNY1vT24dvk2htIvtICEVCH5qSvDAoU8cxiDS-ej2xmrNPR2CTTNKMB8R5kUORzK2d5KSs1OCw";
    // const decoded = jwtDecode(token);
    
    // console.log(decoded);

    return url;
}

export function loginStep2Code2Token(): string {

    return '';
}

export function editProfile(pRedirectURL:string) {
    const jsonAzureB2C:SSOAzureB2C = configSsoAzureB2C();
    const userFlow = 'B2C_1_UN_UNDRR_PROFILE_EDITING';
    let redirectURL = pRedirectURL.trim();
    redirectURL = encodeURIComponent(redirectURL);
    const url = `${_baseURL()}/authorize?p=${userFlow}&client_id=${jsonAzureB2C.client_id}&nonce=defaultNonce&redirect_uri=${redirectURL}&scope=openid&response_type=code&prompt=none`;
    
}

export function passwordReset(pRedirectURL:string) {
    const jsonAzureB2C:SSOAzureB2C = configSsoAzureB2C();
    const userFlow = 'B2C_1_UN_UNDRR_PASSWORD_RESET';
    let redirectURL = pRedirectURL.trim();
    redirectURL = encodeURIComponent(redirectURL);
    const url = `${_baseURL()}/authorize?p=${userFlow}&client_id=${jsonAzureB2C.client_id}&nonce=defaultNonce&redirect_uri=${redirectURL}&scope=openid&response_type=code&prompt=none`;
}

/*
B2C_1_UN_UNDRR_PASSWORD_RESET
https://unb2c.b2clogin.com/unb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_UN_UNDRR_PASSWORD_RESET&client_id=b12b15b7-889a-41c5-a0bf-50b8d31a68a2&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fdrupal-testing.undrr.org%2Flogin%2Foauth2%2Fauthentication%2Funb2c%2Fcallback&scope=openid&response_type=code&prompt=login


B2C_1_UN_UNDRR_PROFILE_EDITING
https://unb2c.b2clogin.com/unb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_UN_UNDRR_PASSWORD_RESET&client_id=b12b15b7-889a-41c5-a0bf-50b8d31a68a2&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fdrupal-testing.undrr.org%2Flogin%2Foauth2%2Fauthentication%2Funb2c%2Fcallback&scope=openid&response_type=code&prompt=login


B2C_1_UN_UNDRR_SIGNUP_SIGNIN
https://unb2c.b2clogin.com/unb2c.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_UN_UNDRR_SIGNUP_SIGNIN&client_id=b12b15b7-889a-41c5-a0bf-50b8d31a68a2&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fdrupal-testing.undrr.org%2Flogin%2Foauth2%2Fauthentication%2Funb2c%2Fcallback&scope=openid&response_type=code&prompt=login
/** */