import { Form, useLoaderData, useActionData, useNavigation } from "react-router";
import { formStringData } from "~/utils/httputil";
import {
	authAction,
	authActionGetAuth,
	authLoader,
	authLoaderGetAuth,
} from "~/utils/auth";
import {
	setTotpEnabled,
	generateTotpIfNotSet,
} from "~/backend.server/models/user/totp";
import {
	getCountrySettingsFromSession,
	redirectWithMessage,
} from "~/utils/session";
import { MainContainer } from "~/frontend/container";
import { redirectLangFromRoute } from "~/utils/url.backend";

import { ViewContext } from "~/frontend/context";
import { BackendContext } from "~/backend.server/context";
import { Card } from "primereact/card";
import { InputMask } from "primereact/inputmask";
import { Button } from "primereact/button";
import { Message } from "primereact/message";

type TotpFormErrors = {
	form?: string[];
	code?: string[];
};

export const action = authAction(async (actionArgs) => {
	const ctx = new BackendContext(actionArgs);
	const { request } = actionArgs;
	const { user } = authActionGetAuth(actionArgs);
	const formData = formStringData(await request.formData());
	const settings = await getCountrySettingsFromSession(request);

	const token = formData.code || "";

	const totpIssuer = settings?.totpIssuer || "";
	const res = await setTotpEnabled(user.id, token, true, totpIssuer);

	let errors: TotpFormErrors = {};
	if (!res.ok) {
		errors.form = [res.error];
		return { ok: false, errors: errors };
	}

	return redirectWithMessage(actionArgs, "/", {
		type: "info",
		text: ctx.t({
			code: "common.totp_enabled",
			msg: "TOTP enabled",
		}),
	});
});

export const loader = authLoader(async (loaderArgs) => {
	const { request } = loaderArgs;
	const { user } = authLoaderGetAuth(loaderArgs);
	if (user.totpEnabled) {
		return redirectLangFromRoute(loaderArgs, "/user/totp-disable");
	}

	const settings = await getCountrySettingsFromSession(request);
	let totpIssuer = "";
	if (settings) {
		totpIssuer = settings.totpIssuer;
	}

	const res = await generateTotpIfNotSet(user.id, totpIssuer);

	return {
		...res,
	};
});

export default function Screen() {
	const ld = useLoaderData<typeof loader>();
	const ctx = new ViewContext();

	const ad = useActionData<typeof action>();
	const errors: TotpFormErrors = ad?.errors || {};
	const data = { code: "" };
	const navigation = useNavigation();
	const isSubmitting = navigation.state === "submitting";

	if (!ld.ok) {
		return (
			<>
				<p>
					{ctx.t({
						code: "user.totp_already_enabled",
						msg: "TOTP already enabled",
					})}
				</p>
			</>
		);
	}

	const qrCodeUrl = ctx.url(
		`/api/qrcode?text=` + encodeURIComponent(ld.secretUrl),
	);

	const stepTitle = ctx.t({
		code: "user.totp_setup_steps_title",
		msg: "Set Up Two-Factor Authentication",
	});
	const stepOne = ctx.t({
		code: "user.totp_step_1",
		msg: "1. Open your authenticator app (Google Authenticator, Microsoft Authenticator, Authy, etc.).",
	});
	const stepTwo = ctx.t({
		code: "user.totp_step_2",
		msg: "2. Scan the QR code below to add your account.",
	});
	const stepThree = ctx.t({
		code: "user.totp_step_3",
		msg: "3. Enter the 6-digit code generated by your app to confirm setup.",
	});
	const manualKeyTitle = ctx.t({
		code: "user.totp_manual_key",
		msg: "Cannot scan the QR code? Use this setup key:",
	});
	const codeHint = ctx.t({
		code: "user.totp_code_hint",
		msg: "Type the current 6-digit code from your authenticator app.",
	});

	return (
		<MainContainer
			title={ctx.t({ code: "user.enable_totp", msg: "Enable TOTP" })}
		>
			<Form method="post" className="mx-auto w-full max-w-2xl">
				<Card className="w-full">
					<div className="flex flex-col gap-6">
						<div className="rounded-lg border border-blue-100 bg-blue-50 p-4 sm:p-5">
							<h2 className="mb-2 text-base font-semibold text-blue-900 sm:text-lg">
								{stepTitle}
							</h2>
							<ul className="list-disc space-y-1 pl-5 text-sm text-blue-900 sm:text-base">
								<li>{stepOne}</li>
								<li>{stepTwo}</li>
								<li>{stepThree}</li>
							</ul>
						</div>

						{errors.form?.map((error, idx) => (
							<Message
								key={`form-error-${idx}`}
								severity="error"
								text={error}
							/>
						))}

						<div className="flex flex-col items-center gap-3 text-center sm:gap-4">
							<img
								src={qrCodeUrl}
								alt="QR Code"
								className="h-auto w-full max-w-[220px]"
							/>
							<div className="w-full rounded-md border border-gray-200 bg-gray-50 px-3 py-2">
								<p className="mb-1 text-xs font-medium text-gray-700 sm:text-sm">
									{manualKeyTitle}
								</p>
								<p className="break-all text-sm text-gray-900 sm:text-base">{ld.secret}</p>
							</div>
						</div>

						<div className="flex flex-col gap-2">
							<label htmlFor="code" className="font-semibold">
								{ctx.t({
									code: "user.generated_code",
									msg: "Generated Code",
								})}
							</label>
							<p className="text-sm text-gray-600">{codeHint}</p>
							<InputMask
								id="code"
								name="code"
								type="text"
								autoComplete="one-time-code"
								mask="999999"
								slotChar="-"
								defaultValue={data.code}
								className="w-full"
								onInput={(e) => {
									const input = e.currentTarget;
									input.value = input.value.replace(/\D/g, "").slice(0, 6);
								}}
								invalid={Boolean(errors.code?.length)}
							/>
							{errors.code?.map((error, idx) => (
								<Message
									key={`code-error-${idx}`}
									severity="error"
									text={error}
								/>
							))}
						</div>

						<div className="flex justify-end">
							<Button
								type="submit"
								label={ctx.t({
									code: "user.enable_totp_button",
									msg: "Enable TOTP",
								})}
								loading={isSubmitting}
							/>
						</div>
					</div>
				</Card>
			</Form>
		</MainContainer>
	);
}
