name: Deploy Containers

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      IMAGE_NAME: delta-country

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image locally first
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.dev
          push: false
          load: true
          tags: undrr/${{ env.IMAGE_NAME }}

      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: myorg/myapp:${{ github.event.inputs.environment }}-latest
